In [13]:
#building a machine learning for API

In [14]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
df = pd.read_csv("dataset/babies.csv")
df

      case  bwt  gestation  parity   age  height  weight  smoke
0        1  120      284.0       0  27.0    62.0   100.0    0.0
1        2  113      282.0       0  33.0    64.0   135.0    0.0
2        3  128      279.0       0  28.0    64.0   115.0    1.0
3        4  123        NaN       0  36.0    69.0   190.0    0.0
4        5  108      282.0       0  23.0    67.0   125.0    1.0
...    ...  ...        ...     ...   ...     ...     ...    ...
1231  1232  113      275.0       1  27.0    60.0   100.0    0.0
1232  1233  128      265.0       0  24.0    67.0   120.0    0.0
1233  1234  130      291.0       0  30.0    65.0   150.0    1.0
1234  1235  125      281.0       1  21.0    65.0   110.0    0.0
1235  1236  117      297.0       0  38.0    65.0   129.0    0.0

[1236 rows x 8 columns]

In [16]:
df.head()

   case  bwt  gestation  parity   age  height  weight  smoke
0     1  120      284.0       0  27.0    62.0   100.0    0.0
1     2  113      282.0       0  33.0    64.0   135.0    0.0
2     3  128      279.0       0  28.0    64.0   115.0    1.0
3     4  123        NaN       0  36.0    69.0   190.0    0.0
4     5  108      282.0       0  23.0    67.0   125.0    1.0

In [17]:
df.describe()

,case,bwt,gestation,parity,age,height,weight,smoke
count,1236.000000,1236.000000,1223.000000,1236.000000,1234.000000,1214.000000,1200.000000,1226.000000
mean,618.500000,119.576861,279.338512,0.254854,27.255267,64.047776,128.625833,0.394780
std,356.946775,18.236452,16.027693,0.435956,5.781405,2.533409,20.971862,0.489003
min,1.000000,55.000000,148.000000,0.000000,15.000000,53.000000,87.000000,0.000000
25%,309.750000,108.750000,272.000000,0.000000,23.000000,62.000000,114.750000,0.000000
50%,618.500000,120.000000,280.000000,0.000000,26.000000,64.000000,125.000000,0.000000
75%,927.250000,131.000000,288.000000,1.000000,31.000000,66.000000,139.000000,1.000000
max,1236.000000,176.000000,353.000000,1.000000,45.000000,72.000000,250.000000,1.000000

In [18]:
#checking for missing values
df.isnull().sum()

case          0
bwt           0
gestation    13
parity        0
age           2
height       22
weight       36
smoke        10
dtype: int64

In [19]:
#removing missing values
df.dropna(inplace=True)

In [20]:
df.isnull().sum()

case         0
bwt          0
gestation    0
parity       0
age          0
height       0
weight       0
smoke        0
dtype: int64

In [21]:
#checking duplicate values
print(df.duplicated().sum())

0

In [22]:
df.columns

Index(['case', 'bwt', 'gestation', 'parity', 'age', 'height', 'weight',
       'smoke'],
      dtype='str')

In [23]:
df.drop(columns=["case"], inplace=True)

In [24]:
df.columns

Index(['bwt', 'gestation', 'parity', 'age', 'height', 'weight', 'smoke'], dtype='str')

In [25]:
df["smoke"].value_counts()

smoke
0.0    715
1.0    459
Name: count, dtype: int64

In [26]:
df["smoke"].value_counts(normalize=True)*100

smoke
0.0    60.902896
1.0    39.097104
Name: proportion, dtype: float64

In [27]:
df.describe()

,bwt,gestation,parity,age,height,weight,smoke
count,1174.000000,1174.000000,1174.000000,1174.000000,1174.000000,1174.000000,1174.000000
mean,119.462521,279.101363,0.262351,27.228279,64.049404,128.478705,0.390971
std,18.328671,16.010305,0.440100,5.817839,2.526102,20.734282,0.488176
min,55.000000,148.000000,0.000000,15.000000,53.000000,87.000000,0.000000
25%,108.000000,272.000000,0.000000,23.000000,62.000000,114.250000,0.000000
50%,120.000000,280.000000,0.000000,26.000000,64.000000,125.000000,0.000000
75%,131.000000,288.000000,1.000000,31.000000,66.000000,139.000000,1.000000
max,176.000000,353.000000,1.000000,45.000000,72.000000,250.000000,1.000000

In [28]:
df.info()

<class 'pandas.DataFrame'>
Index: 1174 entries, 0 to 1235
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   bwt        1174 non-null   int64
 1   gestation  1174 non-null   float64
 2   parity     1174 non-null   int64
 3   age        1174 non-null   float64
 4   height     1174 non-null   float64
 5   weight     1174 non-null   float64
 6   smoke      1174 non-null   float64
dtypes: float64(5), int64(2)
memory usage: 73.4 KB

In [29]:
df.isnull().sum()

bwt          0
gestation    0
parity       0
age          0
height       0
weight       0
smoke        0
dtype: int64

In [30]:
print(df.dropna(inplace=True))

None

In [31]:
df.isnull().sum()

bwt          0
gestation    0
parity       0
age          0
height       0
weight       0
smoke        0
dtype: int64

In [32]:
df.duplicated().sum()

np.int64(0)

In [33]:
#start

In [34]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split as tts

In [35]:
df

      bwt  gestation  parity   age  height  weight  smoke
0     120      284.0       0  27.0    62.0   100.0    0.0
1     113      282.0       0  33.0    64.0   135.0    0.0
2     128      279.0       0  28.0    64.0   115.0    1.0
4     108      282.0       0  23.0    67.0   125.0    1.0
5     136      286.0       0  25.0    62.0    93.0    0.0
...   ...        ...     ...   ...     ...     ...    ...
1231  113      275.0       1  27.0    60.0   100.0    0.0
1232  128      265.0       0  24.0    67.0   120.0    0.0
1233  130      291.0       0  30.0    65.0   150.0    1.0
1234  125      281.0       1  21.0    65.0   110.0    0.0
1235  117      297.0       0  38.0    65.0   129.0    0.0

[1174 rows x 7 columns]

In [36]:
#spliting the data into x and y
y = df["bwt"]
y

0       120
1       113
2       128
4       108
5       136
       ...
1231    113
1232    128
1233    130
1234    125
1235    117
Name: bwt, Length: 1174, dtype: int64

In [37]:
x=df.iloc[:,1:]
x.head()

   gestation  parity   age  height  weight  smoke
0      284.0       0  27.0    62.0   100.0    0.0
1      282.0       0  33.0    64.0   135.0    0.0
2      279.0       0  28.0    64.0   115.0    1.0
4      282.0       0  23.0    67.0   125.0    1.0
5      286.0       0  25.0    62.0    93.0    0.0

In [38]:
#train test split
from sklearn.model_selection import train_test_split as tts

In [39]:
x_train, x_test, y_train, y_test = tts(x,y, test_size=0.2)

In [40]:
x_train.shape

(939, 6)

In [41]:
x_test.shape

(235, 6)

In [42]:
y_train.shape

(939,)

In [43]:
y_test.shape

(235,)

In [44]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge

In [45]:
lr = LinearRegression()
lasso = Lasso()
ridge = Ridge()

In [46]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
x_train = pd.DataFrame(imputer.fit_transform(x_train), columns=x_train.columns)
x_test = pd.DataFrame(imputer.transform(x_test), columns=x_test.columns)

In [47]:
lr.fit(x_train, y_train)
lasso.fit(x_train, y_train)
ridge.fit(x_train, y_train)

Ridge()

In [48]:
lr_pred = lr.predict(x_test)
lasso_pred = lasso.predict(x_test)
ridge_pred = ridge.predict(x_test)

In [61]:
#model evaluation
from sklearn.metrics import mean_squared_error, r2_score

In [62]:
lr_rscore = r2_score(y_test, lr_pred)
lasso_rscore = r2_score(y_test, lasso_pred)
ridge_rscore = r2_score(y_test, ridge_pred)

In [63]:
lr_mse = mean_squared_error(y_test, lr_pred)
lasso_mse = mean_squared_error(y_test, lasso_pred)
ridge_mse = mean_squared_error(y_test, ridge_pred)

In [64]:
print("\nPerformance of Linear Regression Model:")
print("r2_score:", lr_rscore)
print("mse:", lr_mse)

print("\nPerformance of Lasso Regression Model:")
print("r2_score:", lasso_rscore)
print("mse:", lasso_mse)
      
print("\nPerformance of Ridge Regression Model:")
print("r2_score:", ridge_rscore)
print("mse:", ridge_mse)

Performance of Linear Regression Model:
r2_score: 0.29037647204605843
mse: 252.5806679831185

Performance of Lasso Regression Model:
r2_score: 0.27921643836571475
mse: 256.55292742866254

Performance of Ridge Regression Model:
r2_score: 0.29043064589220036
mse: 252.561385552778

In [53]:
import pickle

In [54]:
with open("model/model.pkl", "wb") as f:
    pickle.dump(lr, f)

In [55]:
#loading a pickle file
with open("model/model.pkl", "rb") as obj:
    loaded_model = pickle.load(obj)

In [56]:
x_train.head()

   gestation  parity   age  height  weight  smoke
0      240.0     0.0  26.0    65.0   140.0    0.0
1      278.0     0.0  26.0    70.0   145.0    1.0
2      275.0     1.0  25.0    64.0   125.0    0.0
3      273.0     1.0  22.0    62.0   125.0    0.0
4      260.0     0.0  23.0    61.0    99.0    1.0

In [ ]:
# The model was trained on features: gestation, parity, age, height, weight, smoke
# Do not include the target column 'bwt' in the prediction input.
test_data = {
 "gestation": [279.0],
 "parity": [0.0],
 "age": [38.0],
 "height": [64.0],
 "weight": [124.00000],
 "smoke": [0.0]}

In [69]:
test_df = pd.DataFrame(test_data)
# ensure the test row uses the same feature order as the training data
test_df = test_df.reindex(columns=x_train.columns)
test_df

   gestation  parity   age  height  weight  smoke
0      279.0     0.0  38.0    64.0   124.0    0.0

In [71]:
loaded_model.predict(test_df)

array([123.65232072])